name: Occlusion-Robust-3D-Face-CFR-GAN
channels:
  - pytorch
  - conda-forge
  - pytorch3d
dependencies:
  - python=3.8
  - pip
  - pytorch3d=0.2.5
  - pip:
      - torch
      - torchvision
      - opencv-python
      - pillow
      - scikit-image
      - scipy
      - tensorboard
      - tqdm
